Algoritmo "area Circular"
// Disciplina   : [Lógica de Programação e javascript]
// Professor   : Jailson Costa dos santos
// Descrição   : calcula o valor da area do circulo
// Autor(a)    : Jeferson Fagundes
// Data atual  : 25/08/2021
Var
raio,area:real
Inicio
escreval("digite o raio do circulo")
leia(raio)
area<- pi*(raio*raio)
escreval("a area do circulo é ",area:2:2)
Fimalgoritmo