Algoritmo "area triangular"
// Disciplina   : [Lógica de Programação e javascript]
// Professor   : Jailson Costa dos santos
// Descrição   : calcula o valor da area do triangulo
// Autor(a)    : Jeferson Fagundes
// Data atual  : 25/08/2021
Var
altura,base,area:real
Inicio
escreval("digite a altura do triangulo")
leia(altura)
escreval("digite a base do triangulo")
leia(base)
area<- (altura*base)/2
escreval("a area do triangulo é ",area:2:2)
Fimalgoritmo