Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação e javascript]
// Professor   : Jailson Costa dos santos
// Descrição   : Demonstra o numero antecesso ao valor
// Autor(a)    : Jeferson Fagundes
// Data atual  : 25/08/2021
Var
Valor,Calc:inteiro
Inicio
escreval("digite um valor")
leia(Valor)
Calc<-Valor-1
escreval("o numero antecessor a ",Valor," é ",Calc)


Fimalgoritmo