Algoritmo "Maior_Que_10"
// Disciplina   : [Lógica de Programação e javascript]
// Professor   : Jailson Costa dos santos
// Descrição   : Verifica se o numero é maior que 10
// Autor(a)    : Jeferson Fagundes
// Data atual  : 30/08/2021

Var
// Seção de Declarações das variáveis
valor:inteiro

Inicio
Escreval("Digite um valor: ")
leia(valor)
se valor >10 entao
   Escreval("é maior que 10")
senao
     escreval("é menor ou igual a 10")
fimse
Fimalgoritmo
