Algoritmo "area retangular"
// Disciplina   : [Lógica de Programação e javascript]
// Professor   : Jailson Costa dos santos
// Descrição   : calcula o valor da area do retangulo
// Autor(a)    : Jeferson Fagundes
// Data atual  : 25/08/2021
Var
altura,largura,area:real
Inicio
escreval("digite a altura do retangulo")
leia(altura)
escreval("digite a largura do retangulo")
leia(largura)
area<- altura*largura
escreval("a area do retangulo é ",area:2:2)
Fimalgoritmo