Algoritmo "Soma"
// Disciplina   : [Lógica de Programação e javascript]
// Professor   : Jailson Costa dos santos
// Descrição   : Calcula a soma do valor dado
// Autor(a)    : Jeferson Fagundes
// Data atual  : 25/08/2021
Var
   Num1,Num2:inteiro
   Resultado1: real
Inicio
   escreval("digite o primeiro valor:")
   leia(Num1)
   escreval("digite o segundo valor:")
   leia(Num2)
      Resultado1<- Num1+Num2
      escreval("o valor da soma é = " ,Resultado1)
Fimalgoritmo